version: "3.3"

services:
  nextjs:
    build:
      context: ./
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.nextjs-secure.entrypoints=websecure"
      - "traefik.http.routers.nextjs-secure.rule=Host(`relabel.essenlive.xyz`)"
      - "traefik.http.services.nextjs-service.loadbalancer.server.port=3000"
    networks:
      - proxy
      - default
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env
      
networks:
  proxy:
    external: true