mutation createEconomicEventProduce(
  $agent: ID!
  $unit: ID!
  $note: String = "No description"
  $quantity: Float = 1
  $resourceSpec: ID
  $categories: [ID!]
) {
  createEconomicEvent(
    event: {
      note: $note
      action: "produce" # eg. produce or raise
      provider: $agent # same provider & receiver ? should probably be the org's agent ID (see previous mutation)
      receiver: $agent
      resourceQuantity: { hasUnit: $unit, hasNumericalValue: $quantity }
    }
    newInventoriedResource: { conformsTo: $resourceSpec, tags: $categories }
  ) {
    economicEvent {
      id
      note
      receiver {
        id
        name
        note
      }
      provider {
        id
        name
        note
      }
      resourceQuantity {
        hasNumericalValue
        hasUnit {
          label
          symbol
        }
      }
      resourceInventoriedAs {
        id
        name
        onhandQuantity {
          hasNumericalValue
          hasUnit {
            label
            symbol
          }
        }
        accountingQuantity {
          hasNumericalValue
          hasUnit {
            label
            symbol
          }
        }
      }
    }
    economicResource {
      id
    }
  }
}
