mutation createAgentRelationshipRole($roleLabel: String!) {
  createAgentRelationshipRole(
    agentRelationshipRole: { roleLabel: $roleLabel }
  ) {
    agentRelationshipRole {
      id
      roleLabel
    }
  }
}
